name: pull-request

on:
  - pull_request

env:
  VAULT_TOKEN: github

jobs:
  pull-request:
    name: pull-request
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: false
      VAULT_ADDRESS: http://localhost:8200
    services:
      vault:
        image: vault
        ports: 
          - 8200:8200
        env:
          VAULT_ADDR: ${{env.VAULT_ADDRESS}}
          VAULT_DEV_ROOT_TOKEN_ID: ${{env.VAULT_TOKEN}}    
    steps:    
      - name: checkout
        uses: actions/checkout@v2

      - name: install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: install packages
        run: dotnet restore 

      - name: build
        run: dotnet build
       
      - name: test
        run: dotnet test